### ISSUE TITLE
Subscribe to EEG Datastream

### ISSUE THREAD

**Issue by chowa3** [Emotiv/unity-plugin#15]
Good evening! I am able to subscribe to the raw EEG data stream in Python. However, when I try to do it using the Emotiv Unity Plugin it does not work. I do the following.

0) Define buf to hold the data
double[][] buf = new double[14][];

1) Define the dataStream List
List<string> dataStreamList = new List<string>() {DataStreamName.EEG};

2) Start Connect and Authorize
DataStreamManager.Instance.StartAuthorize();

3) Start the data stream.
DataStreamManager.Instance.StartDataStream(dataStreamList, "EPOCX-REDACTED");

4) Call get EEG data.
DataStreamManager.Instance.GetEEGData(Channel_t.CHAN_AF3);

5) Output to console
Debug.Log(buf[(int)Channels.AF3]);

The problem is that Each time buf[(int)Channels.AF3] contains null. This is the same for all sensors.

**Comment by chowa3** [comment]
![RawEEGScript](https://user-images.githubusercontent.com/74928750/155845444-8e1744ee-ba82-4bcf-a1be-fc71720d0d76.JPG)
![Console](https://user-images.githubusercontent.com/74928750/155845448-a3bb039c-f5a6-4955-aa9e-780538ab3dd1.jpg)

**Comment by chowa3** [comment]
![RawEEGScript](https://user-images.githubusercontent.com/74928750/155845487-b52c76e7-8651-44ad-9e86-dbd86d1293c3.JPG)
![Console](https://user-images.githubusercontent.com/74928750/155845489-5d2ddc96-17fd-4c9a-a5fb-c5c97c277079.jpg)

**Comment by chowa3** [comment]
![RawEEGScript](https://user-images.githubusercontent.com/74928750/155845537-ccec26dc-5478-47be-b828-53d194326caf.JPG)
![Console](https://user-images.githubusercontent.com/74928750/155845541-3431b1f6-59fc-4d6a-8587-dc19db61108b.jpg)

**Comment by tungntEmotiv** [comment]
Hi @chowa3 ,
After step 3, you might need wait some seconds  to the headset is connected and subscribing data.
Could you try below code for step 4 ?
`
if (DataStreamManager.Instance.GetNumberEEGSamples() > 0) {
                string eegHeaderStr = "EEG Header: ";
                string eegDataStr   = "EEG Data: ";
                foreach (var ele in DataStreamManager.Instance.GetEEGChannels()) {
                    string chanStr  = ChannelStringList.ChannelToString(ele);
                    double[] data     = DataStreamManager.Instance.GetEEGData(ele);
                    eegHeaderStr    += chanStr + ", ";
                    if (data != null && data.Length > 0)
                        eegDataStr      +=  data[0].ToString() + ", ";
                    else
                        eegDataStr      +=  "null, "; // for null value
                }
               Debug.Log("eeg channel list: " , eegHeaderStr);
               Debug.Log("eeg data: " , eegDataStr);
            }
`

**Comment by chowa3** [comment]
Hi @tungntEmotiv,
Hope all is well. Unfortunately this did not resolve the error. I tried waiting 7 seconds then again for 30 seconds with the updated code and still received null. It seems like it never makes it past if (DataStreamManager.Instance.GetNumberEEGSamples() > 0)
![Emotiv Code](https://user-images.githubusercontent.com/74928750/157161968-10f7d758-9057-43d8-b295-211be38b7206.JPG)
![Console](https://user-images.githubusercontent.com/74928750/157161973-31d19a27-e48e-4e8e-8724-c9488fa349b1.JPG)

**Comment by tungntEmotiv** [comment]
Hi @chowa3 ,

I suppose that the issue might be caused because there are no slots to handle for SessionActivatedOK and/or LicenseValidTo event at DataStreamManager.cs. Could you help to comment out the line 231 and line 249 at  DataStreamManager.cs ?
If the issue still happen, i think we need to debug via teamview.

**Comment by chowa3** [comment]
Hey @tungntEmotiv,

This allowed me to get further in the process but still received null. 

![Console after commenting lines](https://user-images.githubusercontent.com/74928750/157327810-beb3e4f2-b243-400a-ab02-150f4bd75e2d.JPG)

**Comment by chowa3** [comment]
Before, I didn't get SubscribedOK.

**Comment by tungntEmotiv** [comment]
I think we need to debug via teamviewer. Please help to contact us via https://www.emotiv.com/contact-support/. We will contact you to make appointment for teamviewing.

**Comment by tungntEmotiv** [comment]
@chowa3 , You did resolve this issue, didn't you? We don't hear your feedback. So I will close this issue
