### ISSUE TITLE
Video Tutorial

### ISSUE THREAD

**Issue by Jamie-BureauBeatrice** [Emotiv/unity-plugin#20]
Is it possible to have an official video tutorial made for this?

- Setting up the hardware
- Connecting with Unity (including installation of packages)
- Based on brain activity do call functions

**Comment by hoangphamemotiv** [comment]
Hi @Jamie-BureauBeatrice . we don't have a video tutorial for Unity Plugin yet. Sorry for that. 
at the moment, you can look at the document and examples to see how to integrate it into an app
https://github.com/Emotiv/unity-plugin
https://github.com/Emotiv/cortex-v2-example/tree/master/unity
