### ISSUE TITLE
Error when setting up a new profile

### ISSUE THREAD

**Issue by JendrikDerWeise** [Emotiv/unity-plugin#24]
Hi,
thanks for the Unity-plugin!
I´m trying to setup a new profile through my application. As in the readme written, LoadProfile(string) should look for a existing profile and if is not found, a new profile wil get created and loaded. If I try LoadProfile("whatever") I´m getting 
`An error received: Invalid Parameters.
UnityEngine.Debug:Log (object)
EmotivUnityPlugin.CortexClient:WebSocketClient_MessageReceived (object,WebSocket4Net.MessageReceivedEventArgs) (at Assets/EmotivPlugin/Src/CortexClient.cs:238)`

and

`MessageErrorRecieved :code -32602 message Invalid Parameters.method name setupProfile
UnityEngine.Debug:Log (object)
EmotivUnityPlugin.DataStreamProcess:MessageErrorRecieved (object,EmotivUnityPlugin.ErrorMsgEventArgs) (at Assets/EmotivPlugin/Src/DataStreamProcess.cs:298)`

Also there should be a warning, that using the callbackfunctions to make changes on the UI elements, leads to a total stop of the app. For everybody: use the bools in the EmotivUnityItf instance like the example does in CheckButtonsInteractable ;-)

Looking forward to get some help here :-)

**Comment by tungntEmotiv** [comment]
Hi @JendrikDerWeise ,

Firstly, thank you for reporting the bug. We found that we haven't updated the unity plugin to adapt API change for creating profile. Now we need to set headsetId as required parameter of setupProfile for load. We will update soon for the unity plugin and example. While waiting our update, you can add some below code
1. At TrainingHandler.cs line , add more parameter for method CreateProfile
`
public void CreateProfile(string profileName, string headsetId)
        {
            string cortexToken  = _authorizer.CortexToken;
            _ctxClient.SetupProfile(cortexToken, profileName, "create", headsetId);
        }
`
2. BCITraining.cs , add more headsetId to place where call CreateProfile() for example:
`
_trainingHandler.CreateProfile(profileName, _workingHeadsetId);
`

Thanks

**Comment by JendrikDerWeise** [comment]
Hi,
thank you for your support! This is doing the trick :-)
