### ISSUE TITLE
injectMarkers function may not be set up

### ISSUE THREAD

**Issue by claudkrog** [Emotiv/unity-plugin#5]
Hello,

I see in the Unity Emotiv plug-in that injecting markers into the recorded EEG data is marked as "To do." Will this functionality be added, or could I be given assistance in developing it myself?

Thank you!
C

**Comment by tungntEmotiv** [comment]
Hi @claudkrog ,
Actually, we haven't had release date for inject marker. But we will push this task with higher priority.
In the meantime, You can implement "injectMarker" function by yourself similar to "StartRecord" in RecordManager.cs, we have already prepared "injectMarker" at CtxClient.cs
**Please note that:**
- You might create a Record first then call injectMarker
- Please reference injectMarker api at https://emotiv.gitbook.io/cortex-api/markers/injectmarker

Feel free to contact us, if you have any concern. Thanks

**Comment by claudkrog** [comment]
I tried to implement both injectMarker and updateMarker, by following the way that StartRecord is set up in RecordManager.cs. Similar to StartRecord, I set it up in both SessionHandler and RecordManager. I do not have any errors in my code, however, and the recording is working, and I can export the recording from EmotivPRO. However, when I looked at this exported recording, there are no markers and no labels.  Would it be possible to have more detailed instructions for setting up injectMarker?  Additionally, would updateMarker need to be called immediately after injectMarker in order to set the interval, OR would I call updateMarker at the end of the marker's interval time?  Thank you for the help

**Comment by tungntEmotiv** [comment]
Hi @claudkrog ,

What is result when you call injectMarker? A success response similar to:
`
{
    "id": 1,
    "jsonrpc": "2.0",
    "result": {
        "marker": {
            "endDatetime": "2019-06-06T15:57:41.529661+07:00",
            "extras": {},
            "label": "test2",
            "port": "Cortex Example",
            "startDatetime": "2019-06-06T15:57:41.529661+07:00",
            "type": "instance",
            "uuid": "26fccfd8-e487-4623-910a-1ba8591fcdcf",
            "value": 42
        },
        "recordId": "db01c15e-d916-4a7b-9f1d-16295fd1c643",
        "sessionId": "4cbf7554-31bd-4659-ac58-400b823503f0"
    }
}
`
> Currently I have created a timer in my application, and am using the current time from that as the timestamp parameter. 
Yes, But note that It is the number of **milliseconds** that have elapsed since 00:00:00 Thursday, 1 January 1970 UTC.". 

And what version of your EmotivPRO, I checked on latest EmotivPRO and can see the internal marker value in exported marker csv file. See the attached image
![image](https://user-images.githubusercontent.com/21233798/108677735-adc78400-751c-11eb-8bc5-7e479b1cd09e.png)

> would updateMarker need to be called immediately after injectMarker in order to set the interval, ...
Actually, you only call inject marker with value, and label is enough do not need use updateMarker api. (https://emotiv.gitbook.io/cortex-api/markers/updatemarker)

> What is the difference between startRecord and createRecord?
They are same. the startRecord function to call createRecord api of cortex.

>  Would I need to use the Unity Emotiv LSL to send markers, if I am only using one computer? 
If you create a record in EmotivPRO, you can inject marker via Emotiv LSL. But in your case, i think you need to implement injectMarker on your Application. 

Feel free to contact us if you have any questions.
Thanks

**Comment by claudkrog** [comment]
I am using EmotivPro 2.6.3.335 as well, I do not see markers in the raw data playback in the EmotivPro app. 

If I would like an interval of time, I would need to use updateMarker as well, is that correct?

With my current code, I do not get any response output in the Unity console.

I think my problem is likely with the timestamp. Is there anyway to use my own timer, or do I have to use this 1970 time? How would I get access to this 1970 timestamp? Thank you

**Comment by tungntEmotiv** [comment]
> If I would like an interval of time, I would need to use updateMarker as well, is that correct?

Yes, if you want to turn a "instance" marker into "interval" marker, You will use the updateMarker api to update end time for the marker. 
You can uncomment line 215 in CortexClient.cs to print out the response message to console. Please show us the result.

>  Is there anyway to use my own timer, or do I have to use this....

I mean that the input time of injectMarker api is epoch time at miliseconds. Base on the time, Cortex will inject the marker to right sample of data. 
You can use below function to get current epoch time
`
public static Int64 GetEpochTimeNow()
  {
      TimeSpan t = DateTime.UtcNow - new DateTime(1970, 1, 1);
      Int64 timeSinceEpoch = (Int64)t.TotalMilliseconds;
      return timeSinceEpoch;
  }
`
Thanks

**Comment by claudkrog** [comment]
This is how I have the function set up in SessionHandler:

        // inject marker
        public void InjectMarker(string cortexToken, string sessionId, string label, JToken value, double time, string port = null)
        {
            lock (_locker)
            {
                if (!String.IsNullOrEmpty(_sessionId))
                {
                    _ctxClient.InjectMarker(cortexToken, sessionId, label, value, time, port);
                }
                else
                {
                    UnityEngine.Debug.Log("injectMarker: invalid sessionId.");
                }
            }
        }


I do not see any output when I comment out the Debug line at 215 in CortexClient

**Comment by claudkrog** [comment]
Do I have to use GetEpochTimeNow() in order to have the correct time for a marker (I cannot use my own timer?)

How can I change the duration of a marker? (5 ms, for example) Is it ok if the marker duration is 0?

Will markers only be present in the separate _intervalMarker file, but not in the EEG CSV file? I am assuming that latency refers to the actual time into the application the marker was placed.

Will this intervalMarker file also need to be imported to EEGLAB when working with the EDF files?

I had missed a function with injectMarker - but I am able to inject markers now.

Thanks!

**Comment by tungntEmotiv** [comment]
Hi @claudkrog ,

> 1) Do I have to use GetEpochTimeNow() in order to have the correct time for a marker (I cannot use my own timer?)

You can use your timer. But you have to make sure the time input ~ current epoch time. If the time too far -> you might get an error for injectMarker.

> 2) How can I change the duration of a marker? (5 ms, for example) Is it ok if the marker duration is 0?

You can use updateMarker to update end time of marker ->change duration of interval marker. If you do not update end time of marker , it is an instance marker. so the duration is 0

> 3)Will markers only be present in the separate _intervalMarker file, but not in the EEG CSV file? I am assuming that latency refers to the actual time into the application the marker was placed.

The marker information is included in both EEG CSV and edf file. Cortex will calculate to inject the marker to nearest sample.

`4)` Will this intervalMarker file also need to be imported to EEGLAB when working with the EDF files?

In EDF, CSV exported files has already a marker channel that included all your markers. but to display markers better on EEGLAB, you should import the intervalMarker file also

**Comment by claudkrog** [comment]
In EEGLab, I am not able to see the markers on the EDF file, which I can see in EmotivPro. 

It seems updateMarker may not be working. I am calling injectMarker, then calling updateMarker after 1, 2, or 3 seconds, in order to create a 1, 2 or 3 second interval marker. The Json file states that the marker is however an instance marker, and I only see instance markers in EmotivPro. Additionally, in the CSV marker_interval file, duration stays at "0"

Will I need to make the duration of the marker greater than 0 in order to see markers in EEGlab?

Does the EDF file contain marker information by itself?

I have changed the code in CortexClient.cs (line 201) from if (_nextRequestId > 100)  to if (_nextRequestId > 300), because I was receiving an error about a key code already being assigned.  I did this because I wanted to test 256 markers. Will this code change cause issues? 

Thank you so much!

**Comment by tungntEmotiv** [comment]
Hi @claudkrog ,

About the EEGLab, we will need time to check again.

Could you show us response when you call updateMarker ?  The good response kind of 
`
{
    "id": 1,
    "jsonrpc": "2.0",
    "result": {
        "marker": {
            "endDatetime": "2019-06-06T15:57:49.530743+07:00",
            "extras": {},
            "label": "test2",
            "port": "Cortex Example",
            "startDatetime": "2019-06-06T15:57:41.529661+07:00",
            "type": "interval",
            "uuid": "26fccfd8-e487-4623-910a-1ba8591fcdcf",
            "value": 42
        },
        "recordId": "db01c15e-d916-4a7b-9f1d-16295fd1c643",
        "sessionId": "4cbf7554-31bd-4659-ac58-400b823503f0"
    }
}
`
You can see the type turn to "interval".

What error did you receive? I am not clear about this error " an error about a key code already being assigned" .  
The _nextRequestId is request Id  of a each request. We use different number  for each request to debug easier but it will not cause error.

**Comment by claudkrog** [comment]
Yes, the key code error is below:
![marker_error](https://user-images.githubusercontent.com/25188182/109251073-d5d31380-77b8-11eb-9f0a-7201897eb27a.PNG)

This is one response from updateMarker, from the JSON file:
"Markers": [
        {
            "endDatetime": "2021-02-24T16:11:00.424673-05:00",
            "extras": {
            },
            "index": 1,
            "label": "mymarker",
            "originalEndDatetime": "2021-02-24T16:11:00.426000-05:00",
            "originalStartDatetime": "2021-02-24T16:11:00.426000-05:00",
            "port": "Software",
            "startDatetime": "2021-02-24T16:11:00.424673-05:00",
            "type": "instance",
            "uuid": "3e029fc2-03d8-4559-b0fd-50530df72e36",
            "value": 1
        },
        {

Here is an EDF file, internalMarker file, and CSV file:


[Testing markers_EPOCX_120470_2021.02.24T15.20.46.05.00 - Copy.zip](https://github.com/Emotiv/unity-plugin/files/6047225/Testing.markers_EPOCX_120470_2021.02.24T15.20.46.05.00.-.Copy.zip)


Thank you

**Comment by tungntEmotiv** [comment]
@claudkrog  How long you inject a marker ? I think the above issue because the same requestId added to _methodForRequestId in CortexClient.cs. Actually, We add a new requestId for each request and remove it at WebSocketClient_MessageReceived  function. So In normal case, we will never got the error. It might be too many request sent but only few response message received. Can  try with a lower speed ? Or you also can do if (_nextRequestId > 300), but i think it not good .

With above marker response, i think it seem to response of injectMarker not updateMarker. Please compare the "id" of sent request  and received response. You can uncomment line 194 at CortexClient.cs to show request on console log. Please provide a snap shot of log for us.

**Comment by claudkrog** [comment]
I was trying to inject a marker every 10 milliseconds, 256 times, as this seems to be a good way to test marker timing precision. For this test, I was injecting a marker only, not updating the marker, so the duration was "0".  

For updating markers, when line 194 is uncommented, I can see that the id in the console log goes from 8 (IDs 1-7 seem to be set up throughout the session, record, etc process) all the way until 100, then it goes back to1, 2, 3, 4 and then it gets stuck at id: 5 while the "ArgumentException: An item with the same key has already been added. Key: 5" is present.  Trying this with a lower speed (injecting marker every 100 ms instead of every 10 ms) has the same issue (error at id: 5).  Trying it by injecting a marker every second, and trying to inject a marker every 2 seconds caused the same issue (also error at id: 5)

**Comment by tungntEmotiv** [comment]
Yes, We will check and update the example to make sure the requestId in list is unique.
Beside the unique key error. Do you get another error related to marker? @claudkrog 
Thanks for your raising the issue

**Comment by claudkrog** [comment]
I think I am only seeing this error "ArgumentException: An item with the same key has already been added. Key: 5" 

Please let me know if a way to show markers in EEGLAB is found. Thank you

**Comment by hoangphamemotiv** [comment]
@claudkrog . 
about Emotiv EDF data file, it stores EEG and other information related to EEG and headset as timestamp, interpolation, marker, battery, CQ. it is designed follow EDF standard format. and data in exported EDF file and CSV file are synced and the same. 
because of data value of different data type are different (EEG around 4000, timestamp 1614651445, marker, interpolation channels are small numbers), so when importing all of channels in EEGLAB, they displayed not good, you can fix that by config specific channels or only import EEG channels. 
about displaying marker on EEGLAB, you can import EDF file and marker file.
